### ISSUE TITLE
This seems to be the matplotlib=3.0.0 holdup 

### ISSUE THREAD

**Issue by brianmapes** [weiming9115/MSEplots#2]
Should alpha=0.3 instead of '0.3'? 

Error is: 
~/opt/miniconda3/lib/python3.8/site-packages/matplotlib/artist.py in set_alpha(self, alpha)
 --> 930             raise TypeError('alpha must be a float or None')
TypeError: alpha must be a float or None

Calling line is:
~/opt/miniconda3/lib/python3.8/site-packages/MSEplots/plots.py in msed_plots(pressure, temperature, mixing_ratio, altitude, h0_std, ensemble_size, ent_rate, entrain, ax, fig)
  
--> 425     ax.fill_betweenx(p[lcl_idx:el_idx+1],mse_bp[lcl_idx:el_idx+1],mse_s[lcl_idx:el_idx+1],interpolate=True
    426                     ,color='green',alpha='0.3')

**Comment by brianmapes** [comment]
Update: I edited alpha=0.3 instead of '0.3' and still got the error with latest matplotlib. 
So maybe it is not that simple.

**Comment by brianmapes** [comment]
But the matplotlib=3.0.0 no longer works with python 3.8: 

UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment:Specifications:

  - matplotlib==3.0.0 -> python[version='>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8

**Comment by weiming9115** [comment]
I see. I think the latest matplotlib did some changes in the “fil_between” function.
With 3.0.0 version, it works  and the latest Metypy depends on version 3.0.0 as well.


On Mar 22, 2021, at 2:13 PM, Brian Mapes ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.



Update: I edited alpha=0.3 instead of '0.3' and still got the error with latest matplotlib.
So maybe it is not that simple.

**Comment by weiming9115** [comment]
I don’t know which way is better: changing the python version back to 3.6 with matplotlib 3.00, or updating the mesplot compatible with the latest matplotlib.

The latter might have issues with plotting functions in metpy if you want to use those in the same environment, because they depend on the version 3.00 I suppose.


On Mar 22, 2021, at 2:19 PM, Brian Mapes ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.



But the matplotlib=3.0.0 no longer works with python 3.8:

UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment:Specifications:

  *   matplotlib==3.0.0 -> python[version='>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8

**Comment by brianmapes** [comment]
My debugging skills are not right. 
I edited the code, and reexecuted these
import MSEplots
from MSEplots import plots as mpt

but I still get the same error, even after commenting out the alpha entirely, so the code I edited (and shown in the error stack trace) is not the code being executed! 

--> 425     ax.fill_betweenx(p[lcl_idx:el_idx+1],mse_bp[lcl_idx:el_idx+1],mse_s[lcl_idx:el_idx+1],interpolate=True,
    426                     color='green') #,alpha=0.3)
...
TypeError: alpha must be a float or None

**Comment by weiming9115** [comment]
Problem solved by removing the quotation mark unavailable in the latest matplotlib. 
Now you may try updating the package version into 2.5.3.

**Comment by brianmapes** [comment]
Still doesn't work, sadly. It did overwrite the package code I had edited (the line number is now correct), but the same error persists. Sigh, ne

TypeError                                 Traceback (most recent call last)
--> 425     ax.fill_betweenx(p[lcl_idx:el_idx+1],mse_bp[lcl_idx:el_idx+1],mse_s[lcl_idx:el_idx+1],interpolate=True
    426                     ,color='green',alpha=0.3)

**Comment by weiming9115** [comment]
You did update MSEplots, right? can you check the versions of these packages?

`print("metpy version:",metpy. __version__)`
`print("MSEplots version:",MSEplots.__version__)`
`print("matplotlib version",matplotlib.__version__)`

metpy version: 1.0
MSEplots version: 2.5.3
matplotlib version 3.2.2
The plotting function works well on Colab with the latest version of matplotlib I suppose.
